name: 'Nomad CLI Action'
description: 'Run Nomad CLI commands'
inputs:
  command:
    description: 'Nomad command to run'
    required: true
  token:
    description: 'Nomad token for authentication'
    required: true
  address:
    description: 'Nomad server address'
    required: true
  args:
    description: 'Additional arguments to pass to the command'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'server'
  color: 'purple'
